version: '3'

services:

  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend